
name: Build and Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10']

    steps:
      - uses: actions/checkout@v2
      - name: Testing with version ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Conda list
        shell: bash
        run: conda list
      - name: Install viennarna
        run: |
          conda install -c bioconda viennarna
      - name: Install Python dependencies
        run: |
          conda run -n test python -m pip install --upgrade pip
          conda run -n test pip install -r requirements.txt
      - name: Run Tests
        run: conda run -n test py.test
