name: run with conda
on: [push, pull_request]


jobs:
  create-env:
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        channels: bioconda, conda-forge, defaults
        run:
          conda install viennarna
          pip install .
          pytest


